apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deploy
  labels:
    app: email-service
  annotations:
spec:
  selector:
    matchLabels:
      app: email-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: vking34/vchain-email-service:404ff5e
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        resources:
          requests:
            memory: "256Mi"
            cpu: "80m"
          limits:
            memory: "384Mi"
            cpu: "120m"