apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
    type: NodePort
    selector:
        app: email-service
    ports:
        - port: 50051
          targetPort: 50051
          protocol: TCP