apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deploy
  labels:
    app: payment-service
  annotations:
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: vking34/vchain-payment-service:18af06b
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "384Mi"
            cpu: "100m"