apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
    type: NodePort
    selector:
        app: payment-service
    ports:
        - port: 8082
          targetPort: 8082
          protocol: TCP